name: GLua Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  lua_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TASSIA710/action-glua-lint@master
        with:
          failOnWarning: true
          directory: /lua/